#
# Docker services prepared for development purposes.
#
version: "3.7"
services:
  mongo:
    container_name: performance-lab-mongodb
    image: mongo:4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./../temp/mongodb:/data/db

  mongo-express:
    container_name: performance-lab-dbviewer
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo
